# Generated by Django 4.1.7 on 2023-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='price',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
