# Generated by Django 4.1.7 on 2023-03-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_size_options_price_updatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='sku',
        ),
    ]
