# Generated by Django 4.1.7 on 2023-03-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_code_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='app.size'),
        ),
    ]
