# Generated by Django 4.1.7 on 2023-03-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_price_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='app.size'),
        ),
    ]
